name: 'dbt_payment'
version: '1.0.0'
config-version: 2

profile: 'dbt_payment'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  dbt_payment:
    staging:
      +schema: stg
      +materialized: view
    intermediate:
      +schema: int
      +materialized: ephemeral
    marts:
      +schema: mrt
      +materialized: table
