version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./.data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
